# Generated by Django 4.0.6 on 2022-07-16 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0004_rename_data_response_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('auth_type', models.CharField(choices=[('basic', 'basic'), ('token', 'token'), ('header', 'header'), ('OAuth2', 'OAuth2')], default='basic', max_length=50)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'action',
            },
        ),
        migrations.CreateModel(
            name='ActionAuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField()),
                ('is_valid', models.BooleanField(default=False)),
                ('invalid_reason', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='action.action')),
                ('form', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.form')),
            ],
            options={
                'db_table': 'actionauthconfig',
            },
        ),
    ]
