# Generated by Django 4.0.6 on 2022-07-09 06:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=220)),
            ],
            options={
                'db_table': 'form',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('label', models.CharField(max_length=1024)),
                ('code', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'questionoption',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', 'SINGLE_CHOICE'), ('MULTIPLE_CHOICE', 'MULTIPLE_CHOICE'), ('TEXT', 'TEXT'), ('NUMBER', 'NUMBER'), ('DATE', 'DATE'), ('TIME', 'TIME'), ('NOTE', 'NOTE')], default='SINGLE_CHOICE', max_length=50)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('keyword', models.CharField(max_length=1024)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('allow_none_option', models.BooleanField(default=False)),
                ('allow_all_option', models.BooleanField(default=False)),
                ('lower_limit', models.FloatField(default=1.0)),
                ('upper_limit', models.FloatField(default=100.0)),
                ('allow_decimal', models.BooleanField(default=False)),
                ('date_format', models.CharField(max_length=50)),
                ('time_format', models.CharField(max_length=50)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.form')),
                ('options', models.ManyToManyField(to='store.questionoption')),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
